server:
  port: 8081

spring:
  application:
    name: wanchcoach
  config:
    import: optional:configserver:http://144.24.72.212:8888
  cloud:
    config:
      name: application
      profile: dev

encrypt:
  key: ${ENCRYPT-KEY}